const mongoose = require("mongoose");

const notificationSchema = new mongoose.Schema(
  {
    student: { type: mongoose.Schema.Types.ObjectId, ref: "Student", required: true },

    // Link back to the activity if this notification was auto-generated
    activity: { type: mongoose.Schema.Types.ObjectId, ref: "Activity", default: null },

    title: { type: String, required: true, trim: true },
    message: { type: String, trim: true, default: "" },

    // When the notification should fire / is scheduled for
    triggerAt: { type: Date, required: true },

    // "auto" = generated by the system from an activity, "custom" = created by the student
    source: { type: String, enum: ["auto", "custom"], default: "custom" },

    isRead: { type: Boolean, default: false },
    isSent: { type: Boolean, default: false },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Notification", notificationSchema);
